version: 2
jobs:
    test:
      docker:
      - image: ubuntu:18.04
      working_directory: ~/repos
      steps:
        - checkout
        - run:
            name: apt-get
            command: |
              apt-get update && apt-get install -y gcc && apt-get install -y make && apt-get install -y git && apt-get install -y binutils && apt-get install -y libc6-dev
        - run:
            name: testing
            command: |
              make compile
              chmod a+x test.sh
              make test

workflows:
  version: 2
  test:
    jobs:
      - test